sudo: false
language: java
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- openssl aes-256-cbc -K $encrypted_7da54d832346_key -iv $encrypted_7da54d832346_iv
  -in gce.json.enc -out gce.json -d

script:
- mvn -v
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud -q components install app-engine-java
- gcloud version
- mvn clean test
## https://sonarcloud.io/organizations/ciandt-techgallery/projects
- mvn sonar:sonar -Dsonar.organization=ciandt-techgallery -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=cda2c40ae4bcc42d0970438886b2dcaf9e9c64fb

after_success:
- mvn appengine:update -P production
